In [3]:
import pandas as pd
import numpy as np

# read in .txt file as a dataframe, first line contains columns, subsequent lines contain data with gene name as index
df = pd.read_csv('/home/celeroid/Documents/CLS_MSc/Thesis/EcoCancer/hNITR/phase_1_code/data/Synapse/TCGA/TCGACRC_microarray.txt', sep='\t', index_col=0)

df.head()

,TCGA.AA.3966,TCGA.AA.3994,TCGA.AY.4070,TCGA.AY.4071,TCGA.A6.2670,TCGA.A6.2674,TCGA.A6.2677,TCGA.A6.2678,TCGA.A6.2683,TCGA.AA.3514,...,TCGA.AG.3898,TCGA.AG.3901,TCGA.AG.3902,TCGA.AG.3909,TCGA.AG.3999,TCGA.AG.4001,TCGA.AG.4005,TCGA.AG.4007,TCGA.AG.4008,TCGA.AG.4015
A_23_P104812,0.03,0.86,0.37,0.860,0.64,0.89,0.80,1.395,0.00,0.43,...,0.030,0.51,0.08,0.15,0.470,1.600,0.57,0.65,0.53,-0.14
A_24_P227168,-0.43,0.48,1.23,0.190,0.18,-0.08,0.35,0.320,0.56,0.36,...,0.050,0.09,0.18,0.20,0.230,0.780,0.78,0.34,-0.08,0.13
A_23_P75312,1.18,0.47,-0.22,1.240,-1.25,1.20,-1.47,-1.700,-0.84,1.29,...,0.960,2.16,-0.64,-0.48,1.460,1.000,0.01,-0.83,2.53,-0.02
A_24_P70891,-0.60,-0.42,-0.44,-0.040,0.82,0.66,0.18,-0.220,-1.22,-0.28,...,-0.230,-0.17,-0.03,0.10,-0.479,NaN,NaN,0.16,-0.01,-0.11
A_23_P130954,NaN,-2.15,-3.12,-2.168,-3.13,-2.76,-2.09,-2.900,-1.95,-2.30,...,-1.903,-1.88,-2.25,-2.71,-2.230,-2.614,-2.61,-2.41,-2.20,-2.01